### ISSUE TITLE
テストケースのフォーマットをconfigで設定できるようにして欲しい

### ISSUE THREAD

**Issue by kitagawa-hr** [kyuridenamida/atcoder-tools#140]
現在定数として定義されていますが、例えば以下のようにconfigで設定できたら嬉しいです。

```toml
[etc]
download_without_login=false
parallel_download=false
save_no_session_cache=false
in_example_format = "in_{}.txt"
out_example_format = "out_{}.txt"
```
