### ISSUE TITLE
"soft_unicode" is not supported in latest markupsafe

### ISSUE THREAD

**Issue by shibukazu** [kyuridenamida/atcoder-tools#263]
## Problem
When atcoder-tools is newly installed, the latest version of markupsafe is used.
In that case, we could not execute "atcoder-tools gen" using jinja2.

## Solution
I was able to solve this problem following this step.
1. Clone this repo.
2. Set the version of  markupsafe to 2.0.1. in your local repo like below.
```toml
[tool.poetry.dependencies]
python = "^3.6"
beautifulsoup4 = "^4.9.3"
requests = "^2.25.1"
colorama = "^0.4.4"
toml = "^0.10.2"
Jinja2 = "^2.11.3"
markupsafe = "2.0.1"
```
3. Execute "poetry update", and confirm that the version of markupsafe in poetry.lock is 2.0.1.
4. Execute "pip3 install [your local repo path]"
  
## Ref
- https://github.com/aws/aws-sam-cli/issues/3661
